sp_list = {
    'prog': "prog",
    'cond': "cond",
    "while": "oper_while",
    "break": "oper_break",
    'setq': "setq",
    'read': "read",
    'return': "return_func",
    'plus': "plus",
    'minus': "minus",
    'times': "times",
    'divide': "divide",
    'equal': "equal",
    'nonequal': "nonequal",
    'less': "less",
    'lesseq': "lesseq",
    'greater': "greater",
    'greatereq': "greatereq",
    'and': "oper_and",
    'or': "oper_or",
    'not': "oper_not"
}